pull-bilara

diff --git a/scripts/pull-bilara b/scripts/pull-bilara
--- a/scripts/pull-bilara
+++ b/scripts/pull-bilara
@@ -1,6 +1,10 @@
 #!/bin/bash
 DIR=`dirname $0`
 BRANCH=$1
+
+shopt -s expand_aliases
+alias iferr='if [ "$?" != "0" ]; then '
+
 echo -e "BILARA\t: $0 DIR:$DIR"
 if [ "$BRANCH" == "" ]; then BRANCH=unpublished; fi
 cd ${DIR}/../local/bilara-data > /dev/null
@@ -21,18 +25,20 @@ if git checkout $BRANCH >& /dev/null; then
   echo -e "BILARA\t: on $BRANCH branch" 
 else
   echo -e "BILARA\t: fetching $BRANCH branch" 
-  git track --track origin/$BRANCH $BRANCH
+  git checkout --track origin/$BRANCH 
 fi
 
-echo -e "BILARA\t: Refreshing $BRANCH fork from Github..." && \
-git pull 
+echo -e "BILARA\t: Refreshing sc-voice/$BRANCH ..." 
+git pull origin 
+iferr echo -e "BILARA\t: git pull origin failed (ERROR)"; exit -1; fi
 
+echo -e "BILARA\t: Refreshing suttacentral/$BRANCH ..."
 git fetch suttacentral
-echo -e "BILARA\t: Refreshing $BRANCH fork from suttacentral ..." && \
-git pull -Xtheirs --no-edit https://github.com/suttacentral/bilara-data 
+iferr echo -e "BILARA\t: fetch suttacentral/$BRANCH (ERROR)"; exit -1; fi
+git merge -Xtheirs --no-edit suttacentral/$BRANCH
+iferr echo -e "BILARA\t: merge suttacentral/$BRANCH (ERROR)"; exit -1; fi
 
-echo -e "BILARA\t: Committing $BRANCH changes to bilara-data..." && \
+echo -e "BILARA\t: Committing $BRANCH changes to bilara-data..." 
 git commit -am "SuttaCentral Update" 
-
-echo -e "BILARA\t: Pushing changes to Github..." && \
 git push
+iferr echo -e "BILARA\t: push suttacentral/$BRANCH (ERROR)"; exit -1; fi
